### ISSUE TITLE
Fix YML to updated Website Menu for Tool Sites

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#433]
I just noticed while exploring https://tools.riverscapes.xyz/brat/ that the menus are wrong.

![image](https://user-images.githubusercontent.com/9723905/133819585-ca61f9c5-c315-408a-82f8-a56fec14f329.png)

Should be:
``` yml
topmenu:
    - title: "USU Watershed Sciences Department"
      url: https://qcnr.usu.edu/wats/
    - title: "LTPBR"
      url: http://lowtechpbr.restoration.usu.edu/
    - title: "Riverscapes Consortium"
      url: https://riverscapes.xyz
    - title: "Tools"
      url: https://riverscapes.xyz/Tools/
    - title: "Data"
      url: https://data.riverscapes.xyz
    - title: "Maps"
      url: https://maps.riverscapes.xyz

```
